### ISSUE TITLE
Don't work with React HOOKS

### ISSUE THREAD

**Issue by ecatugy** [Azure-Samples/application-insights-react-demo#6]
Please send suporte for react hooks, class componets is obsolete.

**Comment by bryantee** [comment]
Second this

**Comment by FelipeLujan** [comment]
please support hooks

**Comment by ericlau-solid** [comment]
No point in using this extension at all if it doesn't support hooks. Thanks for the heads up.

**Comment by markwolff** [comment]
Hook should be supported with the latest version of the plugin `@3.x`. I'm going to work on getting a cohesive tracking story / docs for hooks going forward. For now, the example in this repo will work. Eventually I would want the HOC to go away and be taken care of via the plugin so that only `App.jsx` is required in this repo.
