### ISSUE TITLE
Example project doesn't work (React 16.9)

### ISSUE THREAD

**Issue by kachihro** [Azure-Samples/application-insights-react-demo#9]
### This issue is for a: (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
* Followed the steps
* npm install
* npm start - first button has an error

### Any log messages given by the failure
Uncaught TypeError: Cannot read property 'trackTrace' of null
(The "ai" object is undefined)

### Expected/desired behavior
Example for Application Insights

### OS and Version?
Windows 10

?? Is this due to a REACT update - using 16.9 ?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by markwolff** [comment]
The demo was originally written assuming an ikey would be provided. If it isn't a cryptic error is given since it won't bother initializing the SDK altogether. I've updated it to pass a dummy string if none is provided, the telemetry will just be rejected by the ingestion server (you will see errors in your console! But it won't crash your app). Try it again and let me know how it goes

**Comment by muzamuba** [comment]
Hi, 
I am new to typescript and react and I am using the demo project in my React (typescript) project, however I am unable to use the export statement in typescript. Can you please give me some tips or point in a direction on how to use this AppInsights with React-typescript ? 

export const getAppInsights = () => appInsights;

Thank you
